[variables]
DATABASE_URL = "postgresql://dummy:dummy@localhost:5432/dummy"

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "npm run build", "cp -r .next/static .next/standalone/.next/static", "cp -r public .next/standalone/public"]

[start]
cmd = "npx prisma db push --skip-generate && node .next/standalone/server.js"
